var annotated_dup =
[
    [ "loki", null, [
      [ "arima", null, [
        [ "ArimaAnalyzer", "classloki_1_1arima_1_1_arima_analyzer.html", "classloki_1_1arima_1_1_arima_analyzer" ],
        [ "ArimaFitter", "classloki_1_1arima_1_1_arima_fitter.html", "classloki_1_1arima_1_1_arima_fitter" ],
        [ "ArimaFitterConfig", "structloki_1_1arima_1_1_arima_fitter_config.html", "structloki_1_1arima_1_1_arima_fitter_config" ],
        [ "ArimaForecaster", "classloki_1_1arima_1_1_arima_forecaster.html", "classloki_1_1arima_1_1_arima_forecaster" ],
        [ "ArimaOrder", "structloki_1_1arima_1_1_arima_order.html", "structloki_1_1arima_1_1_arima_order" ],
        [ "ArimaOrderSelector", "classloki_1_1arima_1_1_arima_order_selector.html", "classloki_1_1arima_1_1_arima_order_selector" ],
        [ "ArimaOrderSelectorConfig", "structloki_1_1arima_1_1_arima_order_selector_config.html", "structloki_1_1arima_1_1_arima_order_selector_config" ],
        [ "ArimaResult", "structloki_1_1arima_1_1_arima_result.html", "structloki_1_1arima_1_1_arima_result" ],
        [ "ForecastResult", "structloki_1_1arima_1_1_forecast_result.html", "structloki_1_1arima_1_1_forecast_result" ],
        [ "PlotArima", "classloki_1_1arima_1_1_plot_arima.html", "classloki_1_1arima_1_1_plot_arima" ],
        [ "SarimaOrder", "structloki_1_1arima_1_1_sarima_order.html", "structloki_1_1arima_1_1_sarima_order" ]
      ] ],
      [ "clustering", null, [
        [ "ClusterInfo", "structloki_1_1clustering_1_1_cluster_info.html", "structloki_1_1clustering_1_1_cluster_info" ],
        [ "ClusteringAnalyzer", "classloki_1_1clustering_1_1_clustering_analyzer.html", "classloki_1_1clustering_1_1_clustering_analyzer" ],
        [ "ClusteringResult", "structloki_1_1clustering_1_1_clustering_result.html", "structloki_1_1clustering_1_1_clustering_result" ],
        [ "ClusterPoint", "structloki_1_1clustering_1_1_cluster_point.html", "structloki_1_1clustering_1_1_cluster_point" ],
        [ "Dbscan", "classloki_1_1clustering_1_1_dbscan.html", "classloki_1_1clustering_1_1_dbscan" ],
        [ "KMeans", "classloki_1_1clustering_1_1_k_means.html", "classloki_1_1clustering_1_1_k_means" ],
        [ "PlotClustering", "classloki_1_1clustering_1_1_plot_clustering.html", "classloki_1_1clustering_1_1_plot_clustering" ]
      ] ],
      [ "evt", null, [
        [ "EvtAnalyzer", "classloki_1_1evt_1_1_evt_analyzer.html", "classloki_1_1evt_1_1_evt_analyzer" ],
        [ "EvtResult", "structloki_1_1evt_1_1_evt_result.html", "structloki_1_1evt_1_1_evt_result" ],
        [ "Gev", "classloki_1_1evt_1_1_gev.html", "classloki_1_1evt_1_1_gev" ],
        [ "GevFitResult", "structloki_1_1evt_1_1_gev_fit_result.html", "structloki_1_1evt_1_1_gev_fit_result" ],
        [ "GoFResult", "structloki_1_1evt_1_1_go_f_result.html", null ],
        [ "Gpd", "classloki_1_1evt_1_1_gpd.html", "classloki_1_1evt_1_1_gpd" ],
        [ "GpdFitResult", "structloki_1_1evt_1_1_gpd_fit_result.html", "structloki_1_1evt_1_1_gpd_fit_result" ],
        [ "PlotEvt", "classloki_1_1evt_1_1_plot_evt.html", "classloki_1_1evt_1_1_plot_evt" ],
        [ "ReturnLevelCI", "structloki_1_1evt_1_1_return_level_c_i.html", "structloki_1_1evt_1_1_return_level_c_i" ],
        [ "ThresholdSelector", "classloki_1_1evt_1_1_threshold_selector.html", "classloki_1_1evt_1_1_threshold_selector" ]
      ] ],
      [ "filter", null, [
        [ "PlotFilter", "classloki_1_1filter_1_1_plot_filter.html", "classloki_1_1filter_1_1_plot_filter" ]
      ] ],
      [ "homogeneity", null, [
        [ "BocpdDetector", "classloki_1_1homogeneity_1_1_bocpd_detector.html", "classloki_1_1homogeneity_1_1_bocpd_detector" ],
        [ "BocpdDetectorConfig", "structloki_1_1homogeneity_1_1_bocpd_detector_config.html", "structloki_1_1homogeneity_1_1_bocpd_detector_config" ],
        [ "ChangePoint", "structloki_1_1homogeneity_1_1_change_point.html", "structloki_1_1homogeneity_1_1_change_point" ],
        [ "ChangePointDetector", "classloki_1_1homogeneity_1_1_change_point_detector.html", "classloki_1_1homogeneity_1_1_change_point_detector" ],
        [ "ChangePointDetectorConfig", "structloki_1_1homogeneity_1_1_change_point_detector_config.html", "structloki_1_1homogeneity_1_1_change_point_detector_config" ],
        [ "ChangePointResult", "structloki_1_1homogeneity_1_1_change_point_result.html", "structloki_1_1homogeneity_1_1_change_point_result" ],
        [ "HomogeneityAnalyzer", "classloki_1_1homogeneity_1_1_homogeneity_analyzer.html", "classloki_1_1homogeneity_1_1_homogeneity_analyzer" ],
        [ "Homogenizer", "classloki_1_1homogeneity_1_1_homogenizer.html", null ],
        [ "HomogenizerConfig", "structloki_1_1homogeneity_1_1_homogenizer_config.html", null ],
        [ "HomogenizerResult", "structloki_1_1homogeneity_1_1_homogenizer_result.html", "structloki_1_1homogeneity_1_1_homogenizer_result" ],
        [ "MultiChangePointDetector", "classloki_1_1homogeneity_1_1_multi_change_point_detector.html", "classloki_1_1homogeneity_1_1_multi_change_point_detector" ],
        [ "MultiChangePointDetectorConfig", "structloki_1_1homogeneity_1_1_multi_change_point_detector_config.html", "structloki_1_1homogeneity_1_1_multi_change_point_detector_config" ],
        [ "OutlierConfig", "structloki_1_1homogeneity_1_1_outlier_config.html", null ],
        [ "PeltDetector", "classloki_1_1homogeneity_1_1_pelt_detector.html", "classloki_1_1homogeneity_1_1_pelt_detector" ],
        [ "PeltDetectorConfig", "structloki_1_1homogeneity_1_1_pelt_detector_config.html", "structloki_1_1homogeneity_1_1_pelt_detector_config" ],
        [ "PlotHomogeneity", "classloki_1_1homogeneity_1_1_plot_homogeneity.html", "classloki_1_1homogeneity_1_1_plot_homogeneity" ],
        [ "SeriesAdjuster", "classloki_1_1homogeneity_1_1_series_adjuster.html", "classloki_1_1homogeneity_1_1_series_adjuster" ],
        [ "SnhtDetector", "classloki_1_1homogeneity_1_1_snht_detector.html", "classloki_1_1homogeneity_1_1_snht_detector" ],
        [ "SnhtDetectorConfig", "structloki_1_1homogeneity_1_1_snht_detector_config.html", "structloki_1_1homogeneity_1_1_snht_detector_config" ]
      ] ],
      [ "kalman", null, [
        [ "EmEstimator", "classloki_1_1kalman_1_1_em_estimator.html", "classloki_1_1kalman_1_1_em_estimator" ],
        [ "EmResult", "structloki_1_1kalman_1_1_em_result.html", "structloki_1_1kalman_1_1_em_result" ],
        [ "FilterStep", "structloki_1_1kalman_1_1_filter_step.html", "structloki_1_1kalman_1_1_filter_step" ],
        [ "KalmanAnalyzer", "classloki_1_1kalman_1_1_kalman_analyzer.html", "classloki_1_1kalman_1_1_kalman_analyzer" ],
        [ "KalmanFilter", "classloki_1_1kalman_1_1_kalman_filter.html", "classloki_1_1kalman_1_1_kalman_filter" ],
        [ "KalmanModel", "structloki_1_1kalman_1_1_kalman_model.html", "structloki_1_1kalman_1_1_kalman_model" ],
        [ "KalmanModelBuilder", "classloki_1_1kalman_1_1_kalman_model_builder.html", "classloki_1_1kalman_1_1_kalman_model_builder" ],
        [ "KalmanResult", "structloki_1_1kalman_1_1_kalman_result.html", "structloki_1_1kalman_1_1_kalman_result" ],
        [ "PlotKalman", "classloki_1_1kalman_1_1_plot_kalman.html", "classloki_1_1kalman_1_1_plot_kalman" ],
        [ "RtsSmoother", "classloki_1_1kalman_1_1_rts_smoother.html", "classloki_1_1kalman_1_1_rts_smoother" ],
        [ "SmootherStep", "structloki_1_1kalman_1_1_smoother_step.html", "structloki_1_1kalman_1_1_smoother_step" ]
      ] ],
      [ "kriging", null, [
        [ "CrossValidationResult", "structloki_1_1kriging_1_1_cross_validation_result.html", "structloki_1_1kriging_1_1_cross_validation_result" ],
        [ "KrigingAnalyzer", "classloki_1_1kriging_1_1_kriging_analyzer.html", "classloki_1_1kriging_1_1_kriging_analyzer" ],
        [ "KrigingPrediction", "structloki_1_1kriging_1_1_kriging_prediction.html", "structloki_1_1kriging_1_1_kriging_prediction" ],
        [ "KrigingResult", "structloki_1_1kriging_1_1_kriging_result.html", "structloki_1_1kriging_1_1_kriging_result" ],
        [ "PlotKriging", "classloki_1_1kriging_1_1_plot_kriging.html", null ],
        [ "VariogramFitResult", "structloki_1_1kriging_1_1_variogram_fit_result.html", "structloki_1_1kriging_1_1_variogram_fit_result" ],
        [ "VariogramPoint", "structloki_1_1kriging_1_1_variogram_point.html", "structloki_1_1kriging_1_1_variogram_point" ]
      ] ],
      [ "math", null, [
        [ "BSplineFitResult", "structloki_1_1math_1_1_b_spline_fit_result.html", "structloki_1_1math_1_1_b_spline_fit_result" ],
        [ "CrossValidationResult", "structloki_1_1math_1_1_cross_validation_result.html", "structloki_1_1math_1_1_cross_validation_result" ],
        [ "CubicSpline", "classloki_1_1math_1_1_cubic_spline.html", "classloki_1_1math_1_1_cubic_spline" ],
        [ "CubicSplineConfig", "structloki_1_1math_1_1_cubic_spline_config.html", "structloki_1_1math_1_1_cubic_spline_config" ],
        [ "CvPoint", "structloki_1_1math_1_1_cv_point.html", null ],
        [ "KrigingBase", "classloki_1_1math_1_1_kriging_base.html", "classloki_1_1math_1_1_kriging_base" ],
        [ "KrigingPrediction", "structloki_1_1math_1_1_kriging_prediction.html", "structloki_1_1math_1_1_kriging_prediction" ],
        [ "NelderMeadResult", "structloki_1_1math_1_1_nelder_mead_result.html", "structloki_1_1math_1_1_nelder_mead_result" ],
        [ "OrdinaryKriging", "classloki_1_1math_1_1_ordinary_kriging.html", "classloki_1_1math_1_1_ordinary_kriging" ],
        [ "RandomizedSvdResult", "structloki_1_1math_1_1_randomized_svd_result.html", "structloki_1_1math_1_1_randomized_svd_result" ],
        [ "SimpleKriging", "classloki_1_1math_1_1_simple_kriging.html", "classloki_1_1math_1_1_simple_kriging" ],
        [ "UniversalKriging", "classloki_1_1math_1_1_universal_kriging.html", "classloki_1_1math_1_1_universal_kriging" ],
        [ "VariogramFitResult", "structloki_1_1math_1_1_variogram_fit_result.html", "structloki_1_1math_1_1_variogram_fit_result" ],
        [ "VariogramPoint", "structloki_1_1math_1_1_variogram_point.html", "structloki_1_1math_1_1_variogram_point" ]
      ] ],
      [ "outlier", null, [
        [ "HatMatrixDetector", "classloki_1_1outlier_1_1_hat_matrix_detector.html", "classloki_1_1outlier_1_1_hat_matrix_detector" ],
        [ "HatMatrixDetectorConfig", "structloki_1_1outlier_1_1_hat_matrix_detector_config.html", "structloki_1_1outlier_1_1_hat_matrix_detector_config" ],
        [ "HatMatrixResult", "structloki_1_1outlier_1_1_hat_matrix_result.html", "structloki_1_1outlier_1_1_hat_matrix_result" ],
        [ "IqrDetector", "classloki_1_1outlier_1_1_iqr_detector.html", "classloki_1_1outlier_1_1_iqr_detector" ],
        [ "MadDetector", "classloki_1_1outlier_1_1_mad_detector.html", "classloki_1_1outlier_1_1_mad_detector" ],
        [ "OutlierCleaner", "classloki_1_1outlier_1_1_outlier_cleaner.html", "classloki_1_1outlier_1_1_outlier_cleaner" ],
        [ "OutlierDetector", "classloki_1_1outlier_1_1_outlier_detector.html", "classloki_1_1outlier_1_1_outlier_detector" ],
        [ "OutlierPoint", "structloki_1_1outlier_1_1_outlier_point.html", "structloki_1_1outlier_1_1_outlier_point" ],
        [ "OutlierResult", "structloki_1_1outlier_1_1_outlier_result.html", "structloki_1_1outlier_1_1_outlier_result" ],
        [ "PlotOutlier", "classloki_1_1outlier_1_1_plot_outlier.html", "classloki_1_1outlier_1_1_plot_outlier" ],
        [ "ZScoreDetector", "classloki_1_1outlier_1_1_z_score_detector.html", "classloki_1_1outlier_1_1_z_score_detector" ]
      ] ],
      [ "qc", null, [
        [ "PlotQc", "classloki_1_1qc_1_1_plot_qc.html", "classloki_1_1qc_1_1_plot_qc" ],
        [ "QcAnalyzer", "classloki_1_1qc_1_1_qc_analyzer.html", "classloki_1_1qc_1_1_qc_analyzer" ],
        [ "QcResult", "structloki_1_1qc_1_1_qc_result.html", "structloki_1_1qc_1_1_qc_result" ]
      ] ],
      [ "regression", null, [
        [ "AnovaTable", "structloki_1_1regression_1_1_anova_table.html", "structloki_1_1regression_1_1_anova_table" ],
        [ "BreuschPaganResult", "structloki_1_1regression_1_1_breusch_pagan_result.html", "structloki_1_1regression_1_1_breusch_pagan_result" ],
        [ "CalibrationRegressor", "classloki_1_1regression_1_1_calibration_regressor.html", "classloki_1_1regression_1_1_calibration_regressor" ],
        [ "HarmonicRegressor", "classloki_1_1regression_1_1_harmonic_regressor.html", "classloki_1_1regression_1_1_harmonic_regressor" ],
        [ "InfluenceMeasures", "structloki_1_1regression_1_1_influence_measures.html", "structloki_1_1regression_1_1_influence_measures" ],
        [ "LinearRegressor", "classloki_1_1regression_1_1_linear_regressor.html", "classloki_1_1regression_1_1_linear_regressor" ],
        [ "NonlinearRegressor", "classloki_1_1regression_1_1_nonlinear_regressor.html", "classloki_1_1regression_1_1_nonlinear_regressor" ],
        [ "PlotRegression", "classloki_1_1regression_1_1_plot_regression.html", "classloki_1_1regression_1_1_plot_regression" ],
        [ "PolynomialRegressor", "classloki_1_1regression_1_1_polynomial_regressor.html", "classloki_1_1regression_1_1_polynomial_regressor" ],
        [ "PredictionPoint", "structloki_1_1regression_1_1_prediction_point.html", "structloki_1_1regression_1_1_prediction_point" ],
        [ "RegressionDiagnostics", "classloki_1_1regression_1_1_regression_diagnostics.html", "classloki_1_1regression_1_1_regression_diagnostics" ],
        [ "RegressionResult", "structloki_1_1regression_1_1_regression_result.html", "structloki_1_1regression_1_1_regression_result" ],
        [ "Regressor", "classloki_1_1regression_1_1_regressor.html", "classloki_1_1regression_1_1_regressor" ],
        [ "RobustRegressor", "classloki_1_1regression_1_1_robust_regressor.html", "classloki_1_1regression_1_1_robust_regressor" ],
        [ "TrendEstimator", "classloki_1_1regression_1_1_trend_estimator.html", "classloki_1_1regression_1_1_trend_estimator" ],
        [ "VifResult", "structloki_1_1regression_1_1_vif_result.html", "structloki_1_1regression_1_1_vif_result" ]
      ] ],
      [ "simulate", null, [
        [ "ArimaSimulator", "classloki_1_1simulate_1_1_arima_simulator.html", "classloki_1_1simulate_1_1_arima_simulator" ],
        [ "KalmanSimulator", "classloki_1_1simulate_1_1_kalman_simulator.html", "classloki_1_1simulate_1_1_kalman_simulator" ],
        [ "ParameterCI", "structloki_1_1simulate_1_1_parameter_c_i.html", "structloki_1_1simulate_1_1_parameter_c_i" ],
        [ "PlotSimulate", "classloki_1_1simulate_1_1_plot_simulate.html", "classloki_1_1simulate_1_1_plot_simulate" ],
        [ "SimulateAnalyzer", "classloki_1_1simulate_1_1_simulate_analyzer.html", "classloki_1_1simulate_1_1_simulate_analyzer" ],
        [ "SimulationResult", "structloki_1_1simulate_1_1_simulation_result.html", "structloki_1_1simulate_1_1_simulation_result" ]
      ] ],
      [ "spectral", null, [
        [ "FftAnalyzer", "classloki_1_1spectral_1_1_fft_analyzer.html", "classloki_1_1spectral_1_1_fft_analyzer" ],
        [ "FftFrame", "structloki_1_1spectral_1_1_fft_frame.html", "structloki_1_1spectral_1_1_fft_frame" ],
        [ "FftParams", "structloki_1_1spectral_1_1_fft_params.html", "structloki_1_1spectral_1_1_fft_params" ],
        [ "LombScargle", "classloki_1_1spectral_1_1_lomb_scargle.html", "classloki_1_1spectral_1_1_lomb_scargle" ],
        [ "LombScargleParams", "structloki_1_1spectral_1_1_lomb_scargle_params.html", "structloki_1_1spectral_1_1_lomb_scargle_params" ],
        [ "PeakDetector", "classloki_1_1spectral_1_1_peak_detector.html", "classloki_1_1spectral_1_1_peak_detector" ],
        [ "PeakDetectorParams", "structloki_1_1spectral_1_1_peak_detector_params.html", "structloki_1_1spectral_1_1_peak_detector_params" ],
        [ "PlotSpectral", "classloki_1_1spectral_1_1_plot_spectral.html", "classloki_1_1spectral_1_1_plot_spectral" ],
        [ "SpectralAnalyzer", "classloki_1_1spectral_1_1_spectral_analyzer.html", "classloki_1_1spectral_1_1_spectral_analyzer" ],
        [ "SpectralPeak", "structloki_1_1spectral_1_1_spectral_peak.html", "structloki_1_1spectral_1_1_spectral_peak" ],
        [ "SpectralResult", "structloki_1_1spectral_1_1_spectral_result.html", "structloki_1_1spectral_1_1_spectral_result" ],
        [ "SpectrogramAnalyzer", "classloki_1_1spectral_1_1_spectrogram_analyzer.html", "classloki_1_1spectral_1_1_spectrogram_analyzer" ],
        [ "SpectrogramParams", "structloki_1_1spectral_1_1_spectrogram_params.html", "structloki_1_1spectral_1_1_spectrogram_params" ],
        [ "SpectrogramResult", "structloki_1_1spectral_1_1_spectrogram_result.html", "structloki_1_1spectral_1_1_spectrogram_result" ]
      ] ],
      [ "spline", null, [
        [ "PlotSpline", "classloki_1_1spline_1_1_plot_spline.html", "classloki_1_1spline_1_1_plot_spline" ],
        [ "SplineAnalyzer", "classloki_1_1spline_1_1_spline_analyzer.html", "classloki_1_1spline_1_1_spline_analyzer" ],
        [ "SplineResult", "structloki_1_1spline_1_1_spline_result.html", "structloki_1_1spline_1_1_spline_result" ]
      ] ],
      [ "ssa", null, [
        [ "PlotSsa", "classloki_1_1ssa_1_1_plot_ssa.html", "classloki_1_1ssa_1_1_plot_ssa" ],
        [ "SsaAnalyzer", "classloki_1_1ssa_1_1_ssa_analyzer.html", "classloki_1_1ssa_1_1_ssa_analyzer" ],
        [ "SsaGroup", "structloki_1_1ssa_1_1_ssa_group.html", "structloki_1_1ssa_1_1_ssa_group" ],
        [ "SsaGrouper", "classloki_1_1ssa_1_1_ssa_grouper.html", "classloki_1_1ssa_1_1_ssa_grouper" ],
        [ "SsaReconstructor", "classloki_1_1ssa_1_1_ssa_reconstructor.html", "classloki_1_1ssa_1_1_ssa_reconstructor" ],
        [ "SsaResult", "structloki_1_1ssa_1_1_ssa_result.html", "structloki_1_1ssa_1_1_ssa_result" ]
      ] ],
      [ "stationarity", null, [
        [ "AdfTest", "classloki_1_1stationarity_1_1_adf_test.html", "classloki_1_1stationarity_1_1_adf_test" ],
        [ "KpssTest", "classloki_1_1stationarity_1_1_kpss_test.html", "classloki_1_1stationarity_1_1_kpss_test" ],
        [ "PpTest", "classloki_1_1stationarity_1_1_pp_test.html", "classloki_1_1stationarity_1_1_pp_test" ],
        [ "StationarityAnalyzer", "classloki_1_1stationarity_1_1_stationarity_analyzer.html", "classloki_1_1stationarity_1_1_stationarity_analyzer" ],
        [ "StationarityResult", "structloki_1_1stationarity_1_1_stationarity_result.html", "structloki_1_1stationarity_1_1_stationarity_result" ],
        [ "TestResult", "structloki_1_1stationarity_1_1_test_result.html", "structloki_1_1stationarity_1_1_test_result" ]
      ] ],
      [ "stats", null, [
        [ "BootstrapConfig", "structloki_1_1stats_1_1_bootstrap_config.html", "structloki_1_1stats_1_1_bootstrap_config" ],
        [ "BootstrapResult", "structloki_1_1stats_1_1_bootstrap_result.html", "structloki_1_1stats_1_1_bootstrap_result" ],
        [ "HypothesisResult", "structloki_1_1stats_1_1_hypothesis_result.html", "structloki_1_1stats_1_1_hypothesis_result" ],
        [ "Metrics", "structloki_1_1stats_1_1_metrics.html", "structloki_1_1stats_1_1_metrics" ],
        [ "PermutationConfig", "structloki_1_1stats_1_1_permutation_config.html", "structloki_1_1stats_1_1_permutation_config" ],
        [ "PermutationResult", "structloki_1_1stats_1_1_permutation_result.html", "structloki_1_1stats_1_1_permutation_result" ],
        [ "Sampler", "classloki_1_1stats_1_1_sampler.html", "classloki_1_1stats_1_1_sampler" ],
        [ "SummaryStats", "structloki_1_1stats_1_1_summary_stats.html", "structloki_1_1stats_1_1_summary_stats" ]
      ] ],
      [ "AdfConfig", "structloki_1_1_adf_config.html", null ],
      [ "AlgorithmException", "classloki_1_1_algorithm_exception.html", null ],
      [ "AppConfig", "structloki_1_1_app_config.html", null ],
      [ "ArimaConfig", "structloki_1_1_arima_config.html", "structloki_1_1_arima_config" ],
      [ "ArimaFitterConfig", "structloki_1_1_arima_fitter_config.html", "structloki_1_1_arima_fitter_config" ],
      [ "ArimaSarimaConfig", "structloki_1_1_arima_sarima_config.html", "structloki_1_1_arima_sarima_config" ],
      [ "BocpdSection", "structloki_1_1_bocpd_section.html", null ],
      [ "BSplineConfig", "structloki_1_1_b_spline_config.html", "structloki_1_1_b_spline_config" ],
      [ "ClassicalDecomposer", "classloki_1_1_classical_decomposer.html", "classloki_1_1_classical_decomposer" ],
      [ "ClassicalDecompositionConfig", "structloki_1_1_classical_decomposition_config.html", "structloki_1_1_classical_decomposition_config" ],
      [ "ClusteringConfig", "structloki_1_1_clustering_config.html", "structloki_1_1_clustering_config" ],
      [ "ClusteringFeatureConfig", "structloki_1_1_clustering_feature_config.html", "structloki_1_1_clustering_feature_config" ],
      [ "ClusteringOutlierConfig", "structloki_1_1_clustering_outlier_config.html", "structloki_1_1_clustering_outlier_config" ],
      [ "ConfigException", "classloki_1_1_config_exception.html", null ],
      [ "ConfigLoader", "classloki_1_1_config_loader.html", "classloki_1_1_config_loader" ],
      [ "ConvergenceException", "classloki_1_1_convergence_exception.html", null ],
      [ "DataException", "classloki_1_1_data_exception.html", null ],
      [ "DataManager", "classloki_1_1_data_manager.html", "classloki_1_1_data_manager" ],
      [ "DbscanClusteringConfig", "structloki_1_1_dbscan_clustering_config.html", "structloki_1_1_dbscan_clustering_config" ],
      [ "DecompositionAnalyzer", "classloki_1_1_decomposition_analyzer.html", "classloki_1_1_decomposition_analyzer" ],
      [ "DecompositionConfig", "structloki_1_1_decomposition_config.html", "structloki_1_1_decomposition_config" ],
      [ "DecompositionResult", "structloki_1_1_decomposition_result.html", "structloki_1_1_decomposition_result" ],
      [ "DeseasonalizationConfig", "structloki_1_1_deseasonalization_config.html", null ],
      [ "Deseasonalizer", "classloki_1_1_deseasonalizer.html", "classloki_1_1_deseasonalizer" ],
      [ "DesignMatrix", "classloki_1_1_design_matrix.html", "classloki_1_1_design_matrix" ],
      [ "DetectionConfig", "structloki_1_1_detection_config.html", "structloki_1_1_detection_config" ],
      [ "DirectoryScanner", "classloki_1_1_directory_scanner.html", "classloki_1_1_directory_scanner" ],
      [ "EmaFilter", "classloki_1_1_ema_filter.html", "classloki_1_1_ema_filter" ],
      [ "EmaFilterConfig", "structloki_1_1_ema_filter_config.html", null ],
      [ "EvtBlockMaximaConfig", "structloki_1_1_evt_block_maxima_config.html", "structloki_1_1_evt_block_maxima_config" ],
      [ "EvtCiConfig", "structloki_1_1_evt_ci_config.html", "structloki_1_1_evt_ci_config" ],
      [ "EvtConfig", "structloki_1_1_evt_config.html", "structloki_1_1_evt_config" ],
      [ "EvtDeseasonalizationConfig", "structloki_1_1_evt_deseasonalization_config.html", "structloki_1_1_evt_deseasonalization_config" ],
      [ "EvtThresholdConfig", "structloki_1_1_evt_threshold_config.html", "structloki_1_1_evt_threshold_config" ],
      [ "FileNotFoundException", "classloki_1_1_file_not_found_exception.html", null ],
      [ "Filter", "classloki_1_1_filter.html", "classloki_1_1_filter" ],
      [ "FilterAnalyzer", "classloki_1_1_filter_analyzer.html", "classloki_1_1_filter_analyzer" ],
      [ "FilterConfig", "structloki_1_1_filter_config.html", null ],
      [ "FilterGapFillingConfig", "structloki_1_1_filter_gap_filling_config.html", null ],
      [ "FilterResult", "structloki_1_1_filter_result.html", "structloki_1_1_filter_result" ],
      [ "FilterWindowAdvisor", "classloki_1_1_filter_window_advisor.html", "classloki_1_1_filter_window_advisor" ],
      [ "FilterWindowAdvisorConfig", "structloki_1_1_filter_window_advisor_config.html", "structloki_1_1_filter_window_advisor_config" ],
      [ "GapFiller", "classloki_1_1_gap_filler.html", "classloki_1_1_gap_filler" ],
      [ "GapFillingConfig", "structloki_1_1_gap_filling_config.html", null ],
      [ "GapInfo", "structloki_1_1_gap_info.html", "structloki_1_1_gap_info" ],
      [ "Gnuplot", "classloki_1_1_gnuplot.html", "classloki_1_1_gnuplot" ],
      [ "HatMatrix", "classloki_1_1_hat_matrix.html", "classloki_1_1_hat_matrix" ],
      [ "HomogeneityConfig", "structloki_1_1_homogeneity_config.html", null ],
      [ "ILogger", "classloki_1_1_i_logger.html", null ],
      [ "InputConfig", "structloki_1_1_input_config.html", null ],
      [ "IoException", "classloki_1_1_io_exception.html", null ],
      [ "KalmanConfig", "structloki_1_1_kalman_config.html", "structloki_1_1_kalman_config" ],
      [ "KalmanForecastConfig", "structloki_1_1_kalman_forecast_config.html", "structloki_1_1_kalman_forecast_config" ],
      [ "KalmanNoiseConfig", "structloki_1_1_kalman_noise_config.html", "structloki_1_1_kalman_noise_config" ],
      [ "KernelFilterConfig", "structloki_1_1_kernel_filter_config.html", null ],
      [ "KernelSmoother", "classloki_1_1_kernel_smoother.html", "classloki_1_1_kernel_smoother" ],
      [ "KMeansClusteringConfig", "structloki_1_1_k_means_clustering_config.html", "structloki_1_1_k_means_clustering_config" ],
      [ "KpssConfig", "structloki_1_1_kpss_config.html", null ],
      [ "KrigingConfig", "structloki_1_1_kriging_config.html", "structloki_1_1_kriging_config" ],
      [ "KrigingPredictionConfig", "structloki_1_1_kriging_prediction_config.html", "structloki_1_1_kriging_prediction_config" ],
      [ "KrigingSpatialStation", "structloki_1_1_kriging_spatial_station.html", "structloki_1_1_kriging_spatial_station" ],
      [ "KrigingVariogramConfig", "structloki_1_1_kriging_variogram_config.html", "structloki_1_1_kriging_variogram_config" ],
      [ "LmConfig", "structloki_1_1_lm_config.html", "structloki_1_1_lm_config" ],
      [ "LmResult", "structloki_1_1_lm_result.html", "structloki_1_1_lm_result" ],
      [ "LmSolver", "classloki_1_1_lm_solver.html", "classloki_1_1_lm_solver" ],
      [ "Loader", "classloki_1_1_loader.html", "classloki_1_1_loader" ],
      [ "LoadResult", "structloki_1_1_load_result.html", "structloki_1_1_load_result" ],
      [ "LoessFilter", "classloki_1_1_loess_filter.html", "classloki_1_1_loess_filter" ],
      [ "LoessFilterConfig", "structloki_1_1_loess_filter_config.html", null ],
      [ "Logger", "classloki_1_1_logger.html", "classloki_1_1_logger" ],
      [ "LOKIException", "classloki_1_1_l_o_k_i_exception.html", "classloki_1_1_l_o_k_i_exception" ],
      [ "LsqResult", "structloki_1_1_lsq_result.html", "structloki_1_1_lsq_result" ],
      [ "LsqSolver", "classloki_1_1_lsq_solver.html", "classloki_1_1_lsq_solver" ],
      [ "LsqSolverConfig", "structloki_1_1_lsq_solver_config.html", "structloki_1_1_lsq_solver_config" ],
      [ "MedianYearSeries", "classloki_1_1_median_year_series.html", "classloki_1_1_median_year_series" ],
      [ "MissingValueException", "classloki_1_1_missing_value_exception.html", null ],
      [ "MovingAverageFilter", "classloki_1_1_moving_average_filter.html", "classloki_1_1_moving_average_filter" ],
      [ "MovingAverageFilterConfig", "structloki_1_1_moving_average_filter_config.html", null ],
      [ "NonlinearConfig", "structloki_1_1_nonlinear_config.html", null ],
      [ "NurbsConfig", "structloki_1_1_nurbs_config.html", "structloki_1_1_nurbs_config" ],
      [ "Observation", "structloki_1_1_observation.html", null ],
      [ "OutlierConfig", "structloki_1_1_outlier_config.html", "structloki_1_1_outlier_config" ],
      [ "OutlierFilterConfig", "structloki_1_1_outlier_filter_config.html", null ],
      [ "OutputConfig", "structloki_1_1_output_config.html", null ],
      [ "ParseException", "classloki_1_1_parse_exception.html", null ],
      [ "PeltSection", "structloki_1_1_pelt_section.html", "structloki_1_1_pelt_section" ],
      [ "Plot", "classloki_1_1_plot.html", "classloki_1_1_plot" ],
      [ "PlotConfig", "structloki_1_1_plot_config.html", "structloki_1_1_plot_config" ],
      [ "PlotDecomposition", "classloki_1_1_plot_decomposition.html", "classloki_1_1_plot_decomposition" ],
      [ "PlotOptionsConfig", "structloki_1_1_plot_options_config.html", null ],
      [ "PpConfig", "structloki_1_1_pp_config.html", null ],
      [ "QcConfig", "structloki_1_1_qc_config.html", "structloki_1_1_qc_config" ],
      [ "QcOutlierConfig", "structloki_1_1_qc_outlier_config.html", null ],
      [ "QcSeasonalConfig", "structloki_1_1_qc_seasonal_config.html", "structloki_1_1_qc_seasonal_config" ],
      [ "RegressionConfig", "structloki_1_1_regression_config.html", null ],
      [ "RegressionGapFillingConfig", "structloki_1_1_regression_gap_filling_config.html", null ],
      [ "SavitzkyGolayFilter", "classloki_1_1_savitzky_golay_filter.html", "classloki_1_1_savitzky_golay_filter" ],
      [ "SavitzkyGolayFilterConfig", "structloki_1_1_savitzky_golay_filter_config.html", null ],
      [ "SeriesMetadata", "structloki_1_1_series_metadata.html", "structloki_1_1_series_metadata" ],
      [ "SeriesTooShortException", "classloki_1_1_series_too_short_exception.html", null ],
      [ "SimulateArimaConfig", "structloki_1_1_simulate_arima_config.html", "structloki_1_1_simulate_arima_config" ],
      [ "SimulateConfig", "structloki_1_1_simulate_config.html", "structloki_1_1_simulate_config" ],
      [ "SimulateInjectGapsConfig", "structloki_1_1_simulate_inject_gaps_config.html", "structloki_1_1_simulate_inject_gaps_config" ],
      [ "SimulateInjectOutliersConfig", "structloki_1_1_simulate_inject_outliers_config.html", "structloki_1_1_simulate_inject_outliers_config" ],
      [ "SimulateInjectShiftsConfig", "structloki_1_1_simulate_inject_shifts_config.html", "structloki_1_1_simulate_inject_shifts_config" ],
      [ "SimulateKalmanConfig", "structloki_1_1_simulate_kalman_config.html", "structloki_1_1_simulate_kalman_config" ],
      [ "SingularMatrixException", "classloki_1_1_singular_matrix_exception.html", null ],
      [ "SnhtSection", "structloki_1_1_snht_section.html", null ],
      [ "SpectralConfig", "structloki_1_1_spectral_config.html", "structloki_1_1_spectral_config" ],
      [ "SpectralFftConfig", "structloki_1_1_spectral_fft_config.html", "structloki_1_1_spectral_fft_config" ],
      [ "SpectralLombScargleConfig", "structloki_1_1_spectral_lomb_scargle_config.html", "structloki_1_1_spectral_lomb_scargle_config" ],
      [ "SpectralPeakConfig", "structloki_1_1_spectral_peak_config.html", "structloki_1_1_spectral_peak_config" ],
      [ "SpectralSpectrogramConfig", "structloki_1_1_spectral_spectrogram_config.html", "structloki_1_1_spectral_spectrogram_config" ],
      [ "SplineConfig", "structloki_1_1_spline_config.html", "structloki_1_1_spline_config" ],
      [ "SplineFilter", "classloki_1_1_spline_filter.html", "classloki_1_1_spline_filter" ],
      [ "SplineFilterConfig", "structloki_1_1_spline_filter_config.html", null ],
      [ "SsaConfig", "structloki_1_1_ssa_config.html", "structloki_1_1_ssa_config" ],
      [ "SsaGroupingConfig", "structloki_1_1_ssa_grouping_config.html", "structloki_1_1_ssa_grouping_config" ],
      [ "SsaReconstructionConfig", "structloki_1_1_ssa_reconstruction_config.html", "structloki_1_1_ssa_reconstruction_config" ],
      [ "SsaWindowConfig", "structloki_1_1_ssa_window_config.html", "structloki_1_1_ssa_window_config" ],
      [ "StationarityConfig", "structloki_1_1_stationarity_config.html", null ],
      [ "StationarityDifferencingConfig", "structloki_1_1_stationarity_differencing_config.html", null ],
      [ "StationarityTestsConfig", "structloki_1_1_stationarity_tests_config.html", null ],
      [ "StatsConfig", "structloki_1_1_stats_config.html", null ],
      [ "StlDecomposer", "classloki_1_1_stl_decomposer.html", "classloki_1_1_stl_decomposer" ],
      [ "StlDecompositionConfig", "structloki_1_1_stl_decomposition_config.html", "structloki_1_1_stl_decomposition_config" ],
      [ "SvdDecomposition", "classloki_1_1_svd_decomposition.html", "classloki_1_1_svd_decomposition" ],
      [ "TimeSeries", "classloki_1_1_time_series.html", "classloki_1_1_time_series" ],
      [ "WeightedMaFilterConfig", "structloki_1_1_weighted_ma_filter_config.html", null ],
      [ "WeightedMovingAverageFilter", "classloki_1_1_weighted_moving_average_filter.html", "classloki_1_1_weighted_moving_average_filter" ]
    ] ],
    [ "TimeStamp", "class_time_stamp.html", "class_time_stamp" ]
];