#!/bin/bash

rm ../Casper/gnuplot/*

rm ../Casper/gnuplot/eps/*

rm -r ../Build/ ../CMakeCache.txt ../CMakeFiles/ ../cmake_install.cmake ../Makefile ../Casper.*

rm -r ../Casper/CMakeFiles/ ../Casper/cmake_install.cmake ../Casper/Makefile