#pragma once

#include <loki/core/config.hpp>
#include <loki/qc/qcResult.hpp>
#include <loki/timeseries/timeSeries.hpp>

#include <string>
#include <vector>

namespace loki::qc {

/**
 * @brief Orchestrates the full quality control pipeline for a single TimeSeries.
 *
 * QcAnalyzer runs five independently-enabled diagnostic sections:
 *   1. Temporal coverage  -- gaps, completeness, sampling uniformity.
 *   2. Descriptive stats  -- mean, std, IQR, skewness, kurtosis, Hurst, JB test.
 *   3. Outlier detection  -- IQR, MAD, Z-score on MA-detrended residuals.
 *   4. Sampling rate      -- median step, non-uniform step fraction.
 *   5. Seasonal consistency -- MedianYearSeries feasibility (auto-disabled sub-hourly).
 *
 * No data modification is performed. The original series is left unchanged.
 *
 * Outputs written to disk:
 *   - Text protocol:  OUTPUT/PROTOCOLS/qc_[dataset]_[component]_protocol.txt
 *   - Flags CSV:      OUTPUT/CSV/qc_[dataset]_[component]_flags.csv
 *
 * Plots are generated by PlotQc and called from run() if the relevant
 * PlotConfig flags are set.
 */
class QcAnalyzer {
public:

    /**
     * @brief Constructs a QcAnalyzer bound to the given application configuration.
     * @param cfg Application configuration. cfg.qc controls all QC sections.
     */
    explicit QcAnalyzer(const AppConfig& cfg);

    /**
     * @brief Runs the full QC pipeline on a single series.
     *
     * Sections are run in order: sampling -> temporal -> stats -> outlier -> seasonal.
     * Sampling is run first so that medianStepSeconds is available to the other sections.
     *
     * @param series      Input time series. Not modified.
     * @param datasetName Stem of the input file (used in output filenames).
     * @return Populated QcResult.
     * @throws DataException if the series has fewer than 4 valid observations.
     */
    QcResult run(const TimeSeries& series, const std::string& datasetName);

private:

    AppConfig m_cfg;

    // -------------------------------------------------------------------------
    // Analysis sections
    // -------------------------------------------------------------------------

    /**
     * @brief Section 4: sampling rate analysis.
     *
     * Computes medianStepSeconds, minStepSeconds, maxStepSeconds, nNonUniform,
     * and uniformityFraction. Run first so other sections can use medianStepSeconds.
     */
    void _analyzeSampling(const TimeSeries& series, QcResult& result) const;

    /**
     * @brief Section 1: temporal coverage analysis.
     *
     * Computes start/end times (MJD, UTC, GPS), expected epoch count,
     * completeness fraction, gap list, longest gap, and median gap length.
     * Calls GapFiller::detectGaps() internally.
     */
    void _analyzeCoverage(const TimeSeries& series, QcResult& result) const;

    /**
     * @brief Section 2: descriptive statistics.
     *
     * Uses loki::stats::summarize() and loki::stats::jarqueBera().
     * Hurst exponent is included only when cfg.qc.hurstEnabled is true.
     */
    void _analyzeStats(const TimeSeries& series, QcResult& result) const;

    /**
     * @brief Section 3: outlier detection.
     *
     * Applies a centered MA filter (window = cfg.qc.maWindowSize) to estimate
     * and remove the trend, then runs the enabled detectors on the residuals.
     * MA edge NaN positions (first/last half-window points) are excluded from
     * detection. Results are stored in result.iqrResult, madResult, zscResult.
     */
    void _analyzeOutliers(const TimeSeries& series, QcResult& result) const;

    /**
     * @brief Section 5: seasonal consistency analysis.
     *
     * Checks MedianYearSeries feasibility: series span >= minSpanYears and
     * per-month coverage >= minMonthCoverage. Auto-disabled when
     * medianStepSeconds > 3600 (sub-hourly data).
     */
    void _analyzeSeasonal(const TimeSeries& series, QcResult& result) const;

    // -------------------------------------------------------------------------
    // Output helpers
    // -------------------------------------------------------------------------

    /**
     * @brief Builds the per-epoch flag vector from detection results.
     *
     * Iterates over iqrResult, madResult, zscResult and OR-combines the
     * appropriate FLAG_* bits. Gap epochs are set to FLAG_GAP.
     */
    void _buildFlags(const TimeSeries& series, QcResult& result) const;

    /**
     * @brief Builds the plain-text recommendation block and stores it in result.
     */
    void _buildRecommendations(QcResult& result) const;

    /**
     * @brief Writes the full protocol text file.
     *
     * Path: cfg.protocolsDir / "qc_[dataset]_[component]_protocol.txt"
     */
    void _writeProtocol(const QcResult& result) const;

    /**
     * @brief Writes the flagging CSV.
     *
     * Path: cfg.csvDir / "qc_[dataset]_[component]_flags.csv"
     * Format: mjd ; utc ; value ; flag
     * Delimiter: semicolon. One row per epoch in the original series.
     */
    void _writeFlagsCsv(const TimeSeries& series, const QcResult& result) const;

    // -------------------------------------------------------------------------
    // Internal helpers
    // -------------------------------------------------------------------------

    /// Returns true when medianStepSeconds > 3600 (sub-hourly data).
    static bool _isSubHourly(double medianStepSeconds);

    /// Extracts valid (non-NaN) values from the series as a plain vector.
    static std::vector<double> _validValues(const TimeSeries& series);

    /// Computes the p-th percentile of a sorted vector via linear interpolation.
    static double _percentile(std::vector<double> sorted, double p);
};

} // namespace loki::qc
